program PE0305
implicit none

print *,"A",ichar("A")
print *,"B",ichar("B")
print *,"C",ichar("C")
print *,"D",ichar("D")
print *,"E",ichar("E")
print *,"F",ichar("F")
print *,"G",ichar("G")
print *,"H",ichar("H")
print *,"I",ichar("I")
print *,"J",ichar("J")
print *,"K",ichar("K")
print *,"L",ichar("L")
print *,"M",ichar("M")
print *,"N",ichar("N")
print *,"O",ichar("O")
print *,"P",ichar("P")
print *,"Q",ichar("Q")
print *,"R",ichar("R")
print *,"S",ichar("S")
print *,"T",ichar("T")
print *,"U",ichar("U")
print *,"V",ichar("V")
print *,"W",ichar("W")
print *,"X",ichar("X")
print *,"Y",ichar("Y")
print *,"Z",ichar("Z")

print *,"0",ichar("0")
print *,"1",ichar("1")
print *,"2",ichar("2")
print *,"3",ichar("3")
print *,"4",ichar("4")
print *,"5",ichar("5")
print *,"6",ichar("6")
print *,"7",ichar("7")
print *,"8",ichar("8")
print *,"9",ichar("9")

print *," ",ichar(" ")
print *,"=",ichar("=")
print *,"+",ichar("+")
print *,"-",ichar("-")
print *,"*",ichar("*")
print *,"/",ichar("/")
print *,"(",ichar("(")
print *,")",ichar(")")
print *,",",ichar(",")
print *,".",ichar(".")
print *,":",ichar(":")
print *,"!",ichar("!")
print *,"""",ichar("""")
print *,"%",ichar("%")
print *,"&",ichar("&")
print *,";",ichar(";")
print *,"<",ichar("<")
print *,">",ichar(">")
print *,"?",ichar("?")
print *,"$",ichar("$")

end program PE0305